//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltimateBlueScreenSimulator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UltimateBlueScreenSimulator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Blue screen simulator plus 1.11 ***
        ///FACE :(
        ///MODERN 16:113:170,255:255:255
        ///W2K 0:0:128,255:255:255
        ///NT34 0:0:168,170:170:170
        ///W9XME 0:0:170,255:255:255
        ///W9XME_HL 170:170:170,0:0:170
        ///--STRINGBUILD START--
        ///Windows//System is busy. //WARNING!//An error has occurred. To continue:
        ///
        ///Press Enter to return to Windows, or
        ///
        ///Press CTRL+ALT+DEL to restart your computer. If you do this,
        ///you will lose any unsaved information in all open applications.
        ///
        ///Error: {0}//Press any key//Altough you can use CTRL+ALT+DEL to quit an [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _default {
            get {
                return ResourceManager.GetString("_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bsodbanner {
            get {
                object obj = ResourceManager.GetObject("bsodbanner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bsodqr {
            get {
                object obj = ResourceManager.GetObject("bsodqr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bsodqr_transparent {
            get {
                object obj = ResourceManager.GetObject("bsodqr_transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap corner_bl {
            get {
                object obj = ResourceManager.GetObject("corner_bl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap corner_br {
            get {
                object obj = ResourceManager.GetObject("corner_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap corner_br1 {
            get {
                object obj = ResourceManager.GetObject("corner_br1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap corner_tl {
            get {
                object obj = ResourceManager.GetObject("corner_tl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap corner_tr {
            get {
                object obj = ResourceManager.GetObject("corner_tr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACPI.sys:ACPI Driver for NT
        ///acpiex.sys:ACPIEx Driver  
        ///afd.sys:Ancillary Function Driver for WinSock  
        ///afunix.sys:AF_UNIX socket provider 
        ///AgileVpn.sys:RAS Agile Vpn Miniport Call Manager 
        ///ahcache.sys:Application Compatibility Cache  
        ///atrfiltr.sys:Example ATR Filter Driver  
        ///bam.sys:BAM Kernel Driver 
        ///BasicDisplay.sys:Microsoft Basic Display Driver
        ///BasicRender.sys:Microsoft Basic Render Driver 
        ///BazisVirtualCDBus.sys:WinCDEmu virtual CDROM bus 
        ///Beep.SYS:BEEP Driver 
        ///bindflt.sys:Windows Bind Filte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CULPRIT_FILES {
            get {
                return ResourceManager.GetString("CULPRIT_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap current {
            get {
                object obj = ResourceManager.GetObject("current", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap current1 {
            get {
                object obj = ResourceManager.GetObject("current1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap failure {
            get {
                object obj = ResourceManager.GetObject("failure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///:del_loop
        ///del BSOD.exe
        ///del vercheck.txt
        ///del hash.txt
        ///if exist BSOD.exe goto del_loop
        ///if exist vercheck.txt goto del_loop
        ///if exist hash.txt goto del_loop
        ///del finish.bat&amp;start UltimateBlueScreenSimulator.exe /doneupdate.
        /// </summary>
        internal static string final {
            get {
                return ResourceManager.GetString("final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MarkusTegelane_element_brandpic {
            get {
                object obj = ResourceManager.GetObject("MarkusTegelane_element_brandpic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap msoftware {
            get {
                object obj = ResourceManager.GetObject("msoftware", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0x00000001	APC_INDEX_MISMATCH
        ///0x00000002	DEVICE_QUEUE_NOT_BUSY
        ///0x00000003	INVALID_AFFINITY_SET
        ///0x00000004	INVALID_DATA_ACCESS_TRAP
        ///0x00000005	INVALID_PROCESS_ATTACH_ATTEMPT
        ///0x00000006	INVALID_PROCESS_DETACH_ATTEMPT
        ///0x00000007	INVALID_SOFTWARE_INTERRUPT
        ///0x00000008	IRQL_NOT_DISPATCH_LEVEL
        ///0x00000009	IRQL_NOT_GREATER_OR_EQUAL
        ///0x0000000A	IRQL_NOT_LESS_OR_EQUAL
        ///0x0000000B	NO_EXCEPTION_HANDLING_SUPPORT
        ///0x0000000C	MAXIMUM_WAIT_OBJECTS_EXCEEDED
        ///0x0000000D	MUTEX_LEVEL_NUMBER_VIOLATION
        ///0x0000000E	NO_USER [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NTERRORDATABASE {
            get {
                return ResourceManager.GetString("NTERRORDATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pending {
            get {
                object obj = ResourceManager.GetObject("pending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rasterNT {
            get {
                object obj = ResourceManager.GetObject("rasterNT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rasters {
            get {
                object obj = ResourceManager.GetObject("rasters", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rasters2 {
            get {
                object obj = ResourceManager.GetObject("rasters2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rasters3 {
            get {
                object obj = ResourceManager.GetObject("rasters3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap success {
            get {
                object obj = ResourceManager.GetObject("success", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap verifile {
            get {
                object obj = ResourceManager.GetObject("verifile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
